version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "weekly"
    time: "03:00"
    day: "sunday"
  open-pull-requests-limit: 100
  milestone: 35
  ignore:
  - dependency-name: "@bbc*"
    versions:
    - ">= 0"
  rebase-strategy: disabled
