name: Psammead CI - Chromatic UI
on:
  create:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - latest
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12']
    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check for changed files.
        id: changed_files
        uses: jackton1/find-changed-files@v1.1
        with:
          files: 'src' # Returns true if any files within the src directory have changed.

      - name: Install Node Modules
        if: steps.changed_files.outputs.files_changed == 'true'
        run: yarn ci:packages

      - name: Chromatic UI Tests
        if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == 'bbc/psammead') && steps.changed_files.outputs.files_changed == 'true'
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
          buildScriptName: 'build:storybook'
          exitOnceUploaded: true
