name: Psammead CI - Change Scanner

on:
  push:
    branches-ignore:
      - latest

jobs:
  build:
    name: Change Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Get Changed Files
        id: changedFiles
        uses: jitterbit/get-changed-files@v1

      - name: Install Node Modules
        if: contains(steps.changedFiles.outputs.all, 'packages')
        run: yarn ci

      - name: Change Scanner
        if: contains(steps.changedFiles.outputs.all, 'packages')
        run: yarn changeScanner
